spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql:/127.0.0.1:5432}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate