spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todo_db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

server:
  port: 8012
  endpoint: "http://localhost:8012"
  region: "test-region"
  instance: "test-instance"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true